# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'yumoPipeline'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    deploymentMode: 'Incremental'

- script:
    sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
    sed -e 's/^port.*/port = 5432/' /etc/postgresql/10/main/postgresql.conf > postgresql.conf
    sudo chown postgres postgresql.conf
    sudo mv postgresql.conf /etc/postgresql/10/main
    sudo service postgresql stop && sudo service postgresql start $DB_VERSION
    echo "Using postgres version $(psql -U postgres -tc 'SHOW server_version')"
    gem update --system
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
    export PATH=$HOME/.yarn/bin:$PATH
  displayName: 'Run a multi-line script'
