apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-aks.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rubyrails
  name: rubyrails
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rubyrails
    spec:
      containers:
      - command:
        - bash
        image: docker.io/jayfely/classroom_rubyrails
        name: classroom-rubyrails
        command: ["/usr/src/app/script/wait-for-it.sh", "db:2345", "--", "/usr/src/app/script/run"]
        ports:
        - containerPort: 5000
        resources: {}
      initContainers:
      - name: init-postgres
        image: busybox
        command: ['sh', '-c', 'until nslookup postgresql; do echo waiting for postgresql; sleep 2; done;']
        stdin: true
        tty: true
      # restartPolicy: Always
status: {}
